apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "morishettynaveentics@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "epaw rcgz bbwd qsaz"
type: Opaque

# Passw0rd@1234